FROM --platform=linux/amd64 ubuntu:22.04 as builder
SHELL ["/bin/bash", "-c"]

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential clang lld gdb bison flex perl \
    python3 python3-dev python3-pip qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools \
    libqt5opengl5-dev libxml2-dev zlib1g-dev doxygen graphviz libwebkit2gtk-4.0-37 pkg-config
RUN pip3 install --user --upgrade numpy pandas matplotlib scipy seaborn posix_ipc

COPY . /omnetpp
WORKDIR /omnetpp
RUN cp configure.user.dist configure.user && \
    sed -i "s/^WITH_OSG=.*/WITH_OSG=no/" configure.user && \
    sed -i "s/^WITH_OSGEARTH=.*/WITH_OSGEARTH=no/" configure.user && \
    sed -i "s/^WITH_QTENV=.*/WITH_QTENV=no/" configure.user
RUN source ./setenv -f && ./configure && make -j8

FROM ubuntu:22.04 as package
COPY --from=builder /omnetpp/bin/opp_msgtool /
COPY --from=builder /omnetpp/lib /deps/
ENV LD_LIBRARY_PATH=/deps
