#!/usr/bin/env -S sh -c "echo >&2 \"Error: You are running this script instead of sourcing it. Make sure to use it as 'source setenv' or '. setenv', otherwise its settings won't take effect.\"; exit 1"

# first argument can be (e.g. 'source setenv -q'):
# -q : do not show banner text on configuration success
# -r : remove an already configured environment

# Get the directory where this script reside using a trick (works differently on bash and zsh)
# On bash, the current script's name is in 'BASH_SOURCE[0]'
if [ "$BASH_VERSION" != "" ]; then # for BASH
  dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
elif [ "$ZSH_VERSION" != "" ]; then # on zsh the script name is in '$0'
  dir=$(cd $(dirname $0) && pwd)
else # other shells are not supported, because we use variable manipulation constructs that are not part of POSIX
  echo "Error: Unrecognized shell, only bash and zsh are supported."
  return 1
fi

# check if dir is really pointing to an omnet++ installation dir
if [ ! -f "$dir/configure.user" -o ! -f "$dir/include/omnetpp.h" -o ! -f "$dir/Version" ]; then
    echo "Error: '$dir' does not look like an OMNeT++ root directory"
    return 1
fi

# check if we are in a properly configured nix shell
if [[ -f /etc/NIXOS && "$name" != "opp_shell" && "$name" != "opp_shell_native" ]]; then
    echo "Error: must be sourced from a properly configured nix shell started by 'nix run .opp_shell' or 'nix develop .opp_shell#native'."
    return 1
fi

# Activate local python virtual environment if present in the root directory.
# You can create a virtual environment with 'python3 -m venv .venv'
# and then install all required packages with 'python3 -m pip install -r python/requirements.txt'
#
# NOTE: the bin/activate script directly sets the PATH variable to a value saved during
# an earlier run of the script to restore the PATH to that state. This may overwrite any
# changes made to the PATH since the last run. Because of this it is EXTREMELY important
# NOT to modify the PATH in the 'setenv' script before activating the virtual env.
# In short, this activation MUST BE at the very beginning of the 'setenv' script.
#
# NOTE: On NixOS we must avoid activating a virtual environment UNLESS we are in an FHS shell
# where all necessary libraries are mapped to their standard locations. Modules (with wheels)
# installed by pip will not work in a standard Nix environment. if /usr/bin/python does
# not exist, it is safe to assume we are in a Nix environment so we should not activate a
# virtual environment.
#
if [ -x /usr/bin/python -a -f "$dir/.venv/bin/activate" ] ; then
  if [ "$1" != "-q" ]; then
    echo "Activating python virtual environment in '$dir/.venv'"
  fi
  source $dir/.venv/bin/activate
fi

# check for HOMEBREW (on macOS) environment and activate dependent packages 
# (Unless we are in a nix shell... In that case the environment should already be set up
# and brew should not be used at all)
if [ "$(uname)" = "Darwin" -a "$(command -v brew)" != "" -a -z "$IN_NIX_SHELL" ]; then
  echo "HOMEBREW detected, activating dependencies (qt@6, bison, flex, pkg-config, make)."
  export PATH="$(brew --prefix qt@6)/bin:$PATH"
  export PATH="$(brew --prefix bison)/bin:$PATH"
  export PATH="$(brew --prefix flex)/bin:$PATH"
  export PATH="$(brew --prefix pkg-config)/bin:$PATH"
  export PATH="$(brew --prefix make)/libexec/gnubin:$PATH"
  export LDFLAGS="-L$(brew --prefix)/lib $LDFLAGS"
  export CFLAGS="-isystem $(brew --prefix)/include $CFLAGS"
fi

function _numargs() { echo $#; }
if [ $(_numargs $dir) -gt 1 ]; then
    echo "Error: Directory name ($dir) must not contain spaces or special characters."
    return 1
fi

# utility functions for path manipulation
opp_path_remove()
{
    [[ -z $2 ]] && return 2
    local value=":$1:"
    value=${value//:$2:/:}
    value=${value#:}
    value=${value%:}
    echo $value
}

opp_path_cleanup()
{
    for varname in "$@"; do
      local value=$(eval echo \$$varname)  # note: we use eval because '${!varname}' works only in bash, and '${(P)varname}' works only in zsh
      while [[ $value == *::* ]] ; do
          value=${value//::/:}
      done
      value=${value#:}
      value=${value%:}
      export $varname="$value"
    done
}

# remove previous environment to prevent the accumulation of path elements
if [ -n "$__omnetpp_root_dir" ]; then
  if [ "$1" = "-r" ]; then
    echo "Removed previous environment for '$__omnetpp_root_dir'."
    dir=
  else
    echo "Warning: overwriting previous environment for '$__omnetpp_root_dir'."
  fi
  export PATH=$(opp_path_remove "$PATH" "$__omnetpp_root_dir/bin")
  export PYTHONPATH=$(opp_path_remove "$PYTHONPATH" "$__omnetpp_root_dir/python")
  export OMNETPP_IMAGE_PATH=$(opp_path_remove "$OMNETPP_IMAGE_PATH" "$__omnetpp_root_dir/images")
  export __omnetpp_root_dir=
  export OMNETPP_RELEASE=
  export QT_SELECT=
  export QT_LOGGING_RULES=
fi

# do not continue if removal was requested
if [ "$1" = "-r" ]; then
    return 0
fi

# macOS specific settings
if [ $(uname) = "Darwin" ]; then
  if [ $(uname -m) = "arm64" ]; then
    if [ -d $dir/tools/macos.x86_64 ]; then
      echo "NOTE: We are running on Apple Silicon, but you have downloaded the x86_64 version of the installation package!"
      echo "Turning on x86_64 emulation by starting a new shell with 'arch -x86_64 /bin/zsh -i' ..."
      export dir; arch -x86_64 /bin/zsh -c 'source $dir/setenv; zsh -i'
      return 1
    fi
    if [ -d $dir/tools/macos.aarch64 ]; then
      TOOLS_DIR=$dir/tools/macos.aarch64
      export PATH=$TOOLS_DIR/bin:$PATH
    fi
  else
    if [ -d $dir/tools/macos.x86_64 ]; then
      TOOLS_DIR=$dir/tools/macos.x86_64
      export PATH=$TOOLS_DIR/bin:$PATH
    fi
  fi
fi


if [ -n "$MSYSTEM" ]; then
  # on Windows MinGW, we need to unset PYTHONPATH to prevent it from being polluted by external python installations
  # especially the ones that use windows style path separators (e.g. C:\Python312\Lib\site-packages)
  export PYTHONPATH=
fi

# Windows/MinGW specific settings for MS ABI compatible build
if [ -n "$MSYSTEM" -a "$MS_ABI" = "yes" ] ; then
  if [ -n "$VCToolsInstallDir" ] ; then
    # add the MS toolchain directories at the beginning of the PATH to hide the default clang compiler
    export PATH=$(cygpath "$VCToolsInstallDir/bin/HostX64/x64"):$(cygpath "$VCINSTALLDIR/Tools/Llvm/x64/bin"):$(cygpath "$VCPKG_ROOT"):$PATH
  else
    echo "Error: MS Visual C++ and Clang installation is required."
  fi
  # dependencies installed from VCPKG
  VCPKGTripletDir=/opt/visualc
  if [ -d $VCPKGTripletDir ] ; then
    export PATH=$(cygpath "$VCPKGTripletDir/bin"):$(cygpath "$VCPKGTripletDir/tools/Qt6/bin"):$PATH
    export OSG_LIBRARY_PATH=$VCPKGTripletDir/plugins
  else
    echo "Error: The /opt/visualc directory must contain the dependencies insalled by 'vcpkg'. See the 'install_vcenv.sh' file for details."
  fi
fi

export PATH="$dir/bin:$PATH"
export PYTHONPATH="$dir/python:$PYTHONPATH"
export OMNETPP_IMAGE_PATH="$dir/images:$OMNETPP_IMAGE_PATH"
export HOSTNAME
export HOST
export QT_SELECT=6 # on systems with qtchooser, switch to Qt6
export QT_LOGGING_RULES='*.warning=false;qt.qpa.*=false' # disable some qt logging

export OMNETPP_RELEASE=$(cat $dir/Version)
export __omnetpp_root_dir=$dir
dir=

if [ "$1" != "-q" ]; then
  echo "Environment for '$OMNETPP_RELEASE' in directory '$__omnetpp_root_dir' is ready."

  if [ ! -f $__omnetpp_root_dir/Makefile.inc ]; then
  cat <<__END__

Type "./configure" and "make" to build the simulation libraries.
When done, type "omnetpp" to start the IDE.
__END__
  fi
fi

# source user specific script if present
if [ -f "$__omnetpp_root_dir/setenv_local" ] ; then
  source $__omnetpp_root_dir/setenv_local
fi

# Mingw doesn't like extra colons in paths, so remove them using a shell function
opp_path_cleanup PATH PYTHONPATH OMNETPP_IMAGE_PATH

