#!/bin/bash
cd $(dirname "$0")

VERSION=$(cat ../../../Version | sed 's/^omnetpp-//')

echo "Building omnetpp-$VERSION-gui docker image for distrobox..."

if [[ ! -f omnetpp-$VERSION-linux-x86_64.tgz ]]; then
    # get a local version if the file is not available in the context
    echo "omnetpp-$VERSION-linux-x86_64.tgz not found in the context, trying to get it from the dist directory"
    cp ../../dist/*omnetpp-$VERSION-linux-x86_64.tgz ./omnetpp-$VERSION-linux-x86_64.tgz
fi
if [[ ! -f omnetpp-$VERSION-linux-x86_64.tgz ]]; then
    # get a version from github if the file is not available in the context
    echo "omnetpp-$VERSION-linux-x86_64.tgz not found in the context, trying to get it from github"
    curl -# -L https://github.com/omnetpp/omnetpp/releases/download/omnetpp-$VERSION/omnetpp-$VERSION-linux-x86_64.tgz -o omnetpp-$VERSION-linux-x86_64.tgz
fi

if [[ ! -f omnetpp-$VERSION-linux-x86_64.tgz ]]; then
    echo "omnetpp-$VERSION-linux-x86_64.tgz not found in the 'dist' directory or on github. Exiting..."
    exit 1
fi

# build the docker image
set -e
docker build --build-arg VERSION=$VERSION -t ghcr.io/omnetpp/omnetpp-gui:u24.04-$VERSION .
rm omnetpp-$VERSION-linux-x86_64.tgz

# generate the distrobox manifest file
sed "s/@VERSION@/$VERSION/g" distrobox-template.ini > ../../dist/omnetpp-$VERSION-distrobox.ini
echo "omnetpp-$VERSION-distrobox.ini generated"
echo
echo "Install with:"
echo "distrobox assemble create --file ../../dist/omnetpp-$VERSION-distrobox.ini"
